name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > arc-access.pem
        chmod 400 arc-access.pem

    - name: Setup Node.js 18.12.0
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'

    - name: SSH into EC2 and Deploy Node.js Server
      run: |
        ssh -o StrictHostKeyChecking=no -i arc-access.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          
          # Navigate to the Node.js app directory or clone the repo
          if [ ! -d "/var/www/node-app" ]; then
            git clone git@github.com:Arccreativestore/arcstore-backend.git /var/www/node-app
          fi
          cd /var/www/node-app

          # Ensure correct branch
          git checkout main
          
          # Pull the latest changes
          git pull origin main

          # Install specific version of Node.js using nvm with sudo
          sudo NVM_DIR="$HOME/.nvm" bash -c "source $NVM_DIR/nvm.sh; nvm install 18.12.0"

          # Install Yarn globally with sudo
          if ! command -v yarn &> /dev/null; then
            sudo npm install -g yarn
          fi

          # Install dependencies using Yarn with sudo
          sudo yarn install --frozen-lockfile

          # Export environment variables from GitHub Secrets
          cat << 'ENV' > .env
          PAYSTACK_BASE_URL=${{ secrets.PAYSTACK_BASE_URL }}
          PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }}
          PAYSTACK_PUBLIC_KEY=${{ secrets.PAYSTACK_PUBLIC_KEY }}
          FREEPIK_BASE_URL=${{ secrets.FREEPIK_BASE_URL }}
          FREEPIK_API_KEY=${{ secrets.FREEPIK_API_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_HOSTNAME_URL=${{ secrets.AWS_HOSTNAME_URL }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          MONGO_URI=${{ secrets.MONGO_URI }}
          PORT=${{ secrets.PORT }}
          ACCESS_SECRETKEY=${{ secrets.ACCESS_SECRETKEY }}
          REFRESH_SECRETKEY=${{ secrets.REFRESH_SECRETKEY }}
          VERIFYEMAIL_SECRETKEY=${{ secrets.VERIFYEMAIL_SECRETKEY }}
          G_HOST=${{ secrets.G_HOST }}
          G_PORT=${{ secrets.G_PORT }}
          G_USER=${{ secrets.G_USER }}
          G_PASSWORD=${{ secrets.G_PASSWORD }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
          FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
          FACEBOOK_CALLBACK_URL=${{ secrets.FACEBOOK_CALLBACK_URL }}
          MJ_APIKEY=${{ secrets.MJ_APIKEY }}
          MJ_SECRETKEY=${{ secrets.MJ_SECRETKEY }}
          ENV

          # Install PM2 globally with sudo
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Start or restart the Node.js app using PM2
          pm2 restart all || pm2 start yarn --name "node-app" -- run start
        EOF
